### ISSUE TITLE
Twitter webhook only work when custom avatar url uploaded

### ISSUE THREAD

**Issue by LikeABoss30** [Re-Ignited-Development/Re-Ignited-Phone#103]
When i create twitter accounts then send tweet the message was not send to the discord but if i upload custom twitter avatar url then i send message, the message sended to the discord
Do you know how to fix this?
Here is the screenshot of the issue ( sorry for my bad english :) )
![Screenshot_7](https://user-images.githubusercontent.com/75431076/103168000-6f864f00-4862-11eb-8247-110d87c49ca2.png)
![Screenshot_8](https://user-images.githubusercontent.com/75431076/103168001-71e8a900-4862-11eb-9296-45588d788c86.png)
![Screenshot_10](https://user-images.githubusercontent.com/75431076/103168002-72813f80-4862-11eb-9136-f5d324dc6dd0.png)
![Screenshot_11](https://user-images.githubusercontent.com/75431076/103168003-7319d600-4862-11eb-97f0-49ee44bdbca2.png)

**Comment by LightmasterDanny** [comment]
Having the same issue.

**Comment by Davinel17** [comment]
im not able to just send a tweet with or without picture 

have you just enable discord webhook and put webhook in twitter.lua to make it work ? 

cause the link says to create a github or idk 

pls let me know , thank you

**Comment by LightmasterDanny** [comment]
> im not able to just send a tweet with or without picture
> 
> have you just enable discord webhook and put webhook in twitter.lua to make it work ?
> 
> cause the link says to create a github or idk
> 
> pls let me know , thank you

Hi, add webhook to twitter.lua and enable it in config.lua. Also make sure to add av avatar to your twitter account.

**Comment by JohnnyS** [comment]
Hello also having this issue only players with avatars show in the webhook but people without do not
How to fix?

@LightmasterDanny  that is all enabled

**Comment by JohnnyS** [comment]
Anyone has a work around for this?

**Comment by Ivannnmmn** [comment]
Add to 298 in "server/twitter.lua"
`if tweet.authorIcon == '/html/static/img/twitter/default_profile.png' then  --If you change the name of the picture in the default header, you need to change (XXXX.png)
    tweet.authorIcon = 'https://upload.wikimedia.org/wikipedia/zh/thumb/9/9f/Twitter_bird_logo_2012.svg/1200px-Twitter_bird_logo_2012.svg.png'  --(image link) Can be changed to the default photo you want
  end`
