### ISSUE TITLE
bank offline

### ISSUE THREAD

**Issue by fantomeus** [Re-Ignited-Development/Re-Ignited-Phone#104]
Hello,

i've put the new version of re-ignited-Phone and when i try to send money to offline with his number i've got this.

ERROR] [MySQL] [gcphone] An error happens on MySQL for query "SELECT JSON_EXTRACT(accounts, '$.bank') AS bank FROM users WHERE identifier = 'XXXXXXXXXXXXXXXXXXX'": ER_SP_DOES_NOT_EXIST: FUNCTION refork.JSON_EXTRACT does not exist

maybe MariaDB doesn't supported by gcphone ?

**Comment by BTNGaming** [comment]
"does not exist"

You didn't install properly. Look at the error closer.
