### ISSUE TITLE
Screenshot Error

### ISSUE THREAD

**Issue by SpearDog** [Re-Ignited-Development/Re-Ignited-Phone#105]
![image](https://user-images.githubusercontent.com/74559844/103232101-3d4c1e80-4942-11eb-9376-fe3c97def053.png)

I don't know why but, this started happening since the last 2 days.
(I didn't do any modifications to the script).

Any help please?

Thanks!

**Comment by thefurrycanadian** [comment]
I have the same error

**Comment by getsik** [comment]
Same here, send help!
