### ISSUE TITLE
Attempt to index a nil value (local 'resp')

### ISSUE THREAD

**Issue by iamKxcper** [Re-Ignited-Development/Re-Ignited-Phone#106]
When trying to send a photo to someone it throws an error and doesn't send the photo at all.
![FiveM_GTAProcess 2020-12-29 21-34-14 Redux Ultra V1](https://user-images.githubusercontent.com/75444625/103312887-aa34e680-4a1e-11eb-9beb-f09f06c66781.png)

**Comment by lord0o** [comment]
what was your solution? thanks
