### ISSUE TITLE
adding mechanic too the phone

### ISSUE THREAD

**Issue by DNDdjay** [Re-Ignited-Development/Re-Ignited-Phone#110]
hii i have tryet to adding mechanic too the phone

but i dont get any message when i am the mechanic

{
      "display": "mechanic",
      "icon": "/html/static/img/icons_app/mech.png",
      "subMenu": [{
          "title": "Send Message",
          "action": "sendMessage",
          "eventName": "esx_addons_gcphone:call",
          "icons": "fa-comments",
          "type": {
            "number": "mechanic"
          }
        },
        {
          "title": "Kald Mekaniker centralen",
          "action": "call",
          "eventName": "gcphone:autoCallNumber",
          "icons": "fa-phone",
          "type": {
            "number": "906-2512"
          }
        }
      ]
    },

**Comment by giannis97** [comment]
change phone this is on broken man..

**Comment by DNDdjay** [comment]
i have change phone 

i am using Crewphone now

**Comment by giannis97** [comment]
> i have change phone
> 
> i am using Crewphone now

Failed to open the referenced table 'twitter_tweets'
When try to install sql

**Comment by giannis97** [comment]
do you know why the messages doesnt go?
is this the phone?https://github.com/JericoFX/gcphone

**Comment by DNDdjay** [comment]
> do you know why the messages doesnt go?
> is this the phone?https://github.com/JericoFX/gcphone

are u using VRP or ESX ???

**Comment by giannis97** [comment]
ESX 1.2

**Comment by DNDdjay** [comment]
ghamttimysql is somthink for VRP so i dont understand why he is using that

**Comment by DNDdjay** [comment]
and its missing the esx_addons_gcphone i think

**Comment by giannis97** [comment]
if it is supporting on VPR then is not for me
ok thank you anyways

**Comment by BTNGaming** [comment]
Phone isn't "Broken". You don't need esx_addons_gcphone. It's built into this one, Something the other phones like CrewPhone (GCPhone revamped and charged for) won't do because common sense is lacking there.

It's working perfectly fine, just gotta use your head.
