### ISSUE TITLE
Camera doesn't work

### ISSUE THREAD

**Issue by LordXenaroth** [Re-Ignited-Development/Re-Ignited-Phone#115]
I installed screenshot-basic correctly, I tried to configure the export via localhost, via imgur and discord webhook, but nothing happens when I click ENTER on camera, no error, nothing, any fix?

**Comment by LordXenaroth** [comment]
Ok I figured out the app "Camera" doesn't work, while when I try to take a photo with twitter app I can do it and the image file is savedo correctly in my image-server on localhost, but the phone closes and I can't send the photo, why?

**Comment by hAKIZOR** [comment]
@LordXenaroth did u fix? right now i have the same problem...

**Comment by Yous3f** [comment]
Same Issue Please someone help

**Comment by LightmasterDanny** [comment]
Same issue here

**Comment by Demonith** [comment]
Selfie wont go off also i have to exit game to remove it from looking my self

**Comment by hdnxxx** [comment]
same

**Comment by Demonith** [comment]
![20210522144326_1](https://user-images.githubusercontent.com/758842/119250024-790bad00-bb9d-11eb-85dc-b9125bc98736.jpg)

In res thats the error when taking pic using twitter

**Comment by m0iises19** [comment]
```
exports['screenshot-basic']:requestScreenshotUpload("https://discordapp.com/api/webhooks/yourdiscordchannelwebhookurl", data.field, function(data)
  local image = json.decode(data)
  DestroyMobilePhone()
  CellCamActivate(false, false)
  cb(json.encode({ url = image.attachments[1].proxy_url }))
end)

**Comment by JohnnyS** [comment]
> ```
> exports['screenshot-basic']:requestScreenshotUpload("https://discordapp.com/api/webhooks/yourdiscordchannelwebhookurl", data.field, function(data)
>   local image = json.decode(data)
>   DestroyMobilePhone()
>   CellCamActivate(false, false)
>   cb(json.encode({ url = image.attachments[1].proxy_url }))
> end)
> ```

Where do you put this?
