### ISSUE TITLE
Error loading script server/server.lua in resource gcphone: @gcphone/server/server.lua:34: attempt to index a nil value (global 'ESX') stack traceback:

### ISSUE THREAD

**Issue by Granata1** [Re-Ignited-Development/Re-Ignited-Phone#116]
Mhm? I get this error in server console.

Error loading script server/server.lua in resource gcphone: @gcphone/server/server.lua:34: attempt to index a nil value (global 'ESX')
stack traceback:
![Screenshot_1](https://user-images.githubusercontent.com/20045163/112179561-77585400-8c03-11eb-912c-cfdf4c37c466.png)

**Comment by Granata1** [comment]
I resolved my problem, my problem was server.cfg I just started those scripts above all ESX scripts.
![Screenshot_2](https://user-images.githubusercontent.com/20045163/112183192-b1772500-8c06-11eb-82ff-df558605254a.png)

**Comment by Madeiradany** [comment]
merci ca aidera les autres
