### ISSUE TITLE
Phone Number is ###-####

### ISSUE THREAD

**Issue by McShmeater** [Re-Ignited-Development/Re-Ignited-Phone#119]
Everytime we try to install a new gcphone from whatever we keep getting the same issue which is that our phone number is not generating we have tried everything if you could help that would be great. thanks.

**Comment by BTNGaming** [comment]
You have to reinstall then, because you installed something incorrectly, or you're using the wrong version of the phone. if you're on es_extended 1.1 or older, use the 1.1 version in releases. and 1.2(final) or newer, use the 1.2 version.
