### ISSUE TITLE
Translation and Vehicle Pan Issue

### ISSUE THREAD

**Issue by GrizzlyRP** [Re-Ignited-Development/Re-Ignited-Phone#12]
"APP_MESSAGE_MESS_NUMBER": "Number ", is missing from english translation :slight_smile:

Also, when you exit the camera mode after taking a picture, and get into a vehicle, your controls are locked up and you cant pan around. when you left click mouse, it stops it and starts working again

**Comment by BTNGaming** [comment]
I will test this out in my server, It could be an issue with the camera trying to take image twice. I will look into this, Thanks for letting us know!

**Comment by GrizzlyRP** [comment]
Cheers

**Comment by BTNGaming** [comment]
I will fix the translation, but I can't reproduce your issue. I took a picture and immediately got into a car and was able to move my camera.

**Comment by BTNGaming** [comment]
Haven't heard anything back in over a week. If this is still an issue, please inform us.
