### ISSUE TITLE
Twitter notification not showing on screen

### ISSUE THREAD

**Issue by JohnnyS** [Re-Ignited-Development/Re-Ignited-Phone#121]
I am using the latest resource and followed the picture however the notifications are still not showing. I downloaded the 2nd download the simple drag and drop.

> The following should remain false"useWebRTCVocal": false as it doesn't work with onesync anymore."
Im not sure where to find this to make sure it is false

I dont see no errors in the console but any help would be appreciated

**Comment by BTNGaming** [comment]
I have tested this repeatedly and found no way to reproduce this issue. If you have this issue still please provide ANY details possible, much appreciated.

**Comment by catiagomes94a** [comment]
I have the same errors and some more from the bank
