### ISSUE TITLE
Phone not ringing

### ISSUE THREAD

**Issue by Davinel17** [Re-Ignited-Development/Re-Ignited-Phone#125]
like the title , 
void is activate , but the phone not ring on call

**Comment by amr-coding** [comment]
> like the title ,
> void is activate , but the phone not ring on call

Have you solved the problem so far?

**Comment by Ivannnmmn** [comment]
gcphone\server\server.lua
Find "elseif hasPhone == 0 then" and replace it with "elseif hasPhone == 0 and Config.ItemRequired then"

**Comment by BTNGaming** [comment]
Added this to the new version that will be up in the next week or two. Thank you for the fix @Ivannnmmn
