### ISSUE TITLE
high mysql ms

### ISSUE THREAD

**Issue by xrtw** [Re-Ignited-Development/Re-Ignited-Phone#138]
hello, is there any chances to make faster mysql writing with gcphone?
https://i.gyazo.com/5e744d99c3f59c741b4ddc54ee15b359.png

**Comment by BTNGaming** [comment]
Are you running on a VPS or shared hosting in ZAP? Where is your server hosted from? VPS/DEDI/SHARED HOSTING? Zap/NFO Servers/OVH/ETC?

**Comment by xrtw** [comment]
dedicated server ovh
