### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Wasted187** [Re-Ignited-Development/Re-Ignited-Phone#139]
I get this error when i try to import the twitter.sql and the base.sql 
-- ENABLE THE BELOW LINE FOR ESX 1.2
-- USE `es_extended`;

-- DISABLE THE BELOW LINE AND ENABLE THE ABOVE LINE FOR ESX 1.2
USE `essentialmode`
MySQL said: Documentation

#1044 - Access denied for user 'zap422940-2'@'%' to database 'essentialmode

**Comment by xLamday** [comment]
Into the file you should change USE >  essentialmode to ---> > USE es_extended
