### ISSUE TITLE
Pictures messaging Issue - Image server ok though

### ISSUE THREAD

**Issue by cthulhuely** [Re-Ignited-Development/Re-Ignited-Phone#140]
Hi,

I've got an issue with the pictures function, looked at documentation tutorial and other issues I didn't found anything really helpful.

I'm using the latest release of reignited phone.
I'm using the latest commit of [screenshot-basic](https://github.com/citizenfx/screenshot-basic)
I had a nodejs server running  the latest commit of [image-server](https://github.com/LoganHeinzelman/image-server) on a distant server.
No script error/warning of any kind while using the phone or taking pics.

When I try to send a picture message through the message app :
It opens up the camera, 
It take the screen shot and send it to the image server without trouble when I press Enter
Then it bring me back to the messaging app where nothing new seems to appear.
So i'm guessing there's an issue with the script on the message creation part ?

here's one of the image on the image-server
![image](https://user-images.githubusercontent.com/11075572/125389343-5b8ae080-e3a1-11eb-91cb-34ad79dc358c.png)

Any way thanks in advance for the help

**Comment by jrence** [comment]
Try to use an discord webhook instead

**Comment by SolidHabu** [comment]
> 
> 
> Try to use an discord webhook instead

So you'd just set that as the url where screenshot-basic is sending things? Just using a discord webhook url?

**Comment by jrence** [comment]
on client side of gcphone yes..

**Comment by jrence** [comment]
instead wasting some money of image server... it will save you alot
