### ISSUE TITLE
cursor does not appear to select on the phone

### ISSUE THREAD

**Issue by boresh53** [Re-Ignited-Development/Re-Ignited-Phone#145]
Hello, I am running the plugin with ESX legacy. I have an issue where I can't see the cursor on the phone so I can't use it. When I move my mouse it makes my character move while I have the phone open. Thank you in advance for your assistance.

**Comment by BTNGaming** [comment]
if the cursor isn't showing up, verify that your phone isn't in keyboard/mouse mode, if it is and the arrows are working fine, go to the SETTINGS section while your phone is opened, and change it to MOUSE.
