### ISSUE TITLE
Incorrect time displayed on message

### ISSUE THREAD

**Issue by LimeSucker** [Re-Ignited-Development/Re-Ignited-Phone#148]
Hello. 

The title is pretty self explanatory : when someone receive a message, even though it has been sent just now, the phone says "two hours ago"
That makes me think there's a problem with the time zone. But I have no idea where I can fix it. Any idea ?
Thanks !

**Comment by BTNGaming** [comment]
To fix this, change the timezone on your server vps/dedi etc.

It uses the time of your server box. Make sure your server box time is accurate and this will auto correct :)
