### ISSUE TITLE
GC phone still not work not compatible with ESX 1.2 Legacy

### ISSUE THREAD

**Issue by Adrianmcmastergaming** [Re-Ignited-Development/Re-Ignited-Phone#151]
I am still having problems with the Re-Ignited-Phone. I have used the 1.2 for because my framework is ESX 1.2 Legacy. We tested it on our server and we can send text messages to one another. GPS but works sometimes but fails and not sure why. We cannot receive phone calls from phone to phone. I noticed you last updated on12/21/2020. So the question is compatibility with ESX Legacy. I am aware since ESX 1.2 final was created ESX has changed a lot. ESX 1.2 Legacy is different. I can also see from comment other are having the same issue as me. I have spoken to the ESX team and they say not sure about compatibility and should ask the developer. I am not a coder so no idea how to update myself but think you might need to make a few updates so its also compatible with ESX 1.2 Legacy because some server owner are upgrading to ESX 1.2 Legacy and having the same problems. There are no other phone mods out there that work with ESX Legacy cos I have tried them all. The default esx_phone works. Me and a lot of other would-be grateful if it could be updated This is the link for ESX 1.2 Legacy created by the esx team. https://github.com/esx-framework/esx-legacy

**Comment by BTNGaming** [comment]
Replied in another comment.
