### ISSUE TITLE
Pressing the A button opens phone

### ISSUE THREAD

**Issue by Megatron101010** [Re-Ignited-Development/Re-Ignited-Phone#156]
I play using a controller, and I noticed when I press the A button it opens the phone. How would I change this?

**Comment by ThatPool** [comment]
_in config.lua_

find **Config.KeyOpenClose**

change the key from 288 to any key you want.
you can find the keys here: https://docs.fivem.net/docs/game-references/controls/

config had default value of 288 for F1 keyboard key and in controls its listed that controller button A will also open phone.
![image](https://user-images.githubusercontent.com/63418483/134466250-194448e7-fef9-4005-a2be-303459f1b488.png)
