### ISSUE TITLE
Camera and GPS

### ISSUE THREAD

**Issue by Brutuss** [Re-Ignited-Development/Re-Ignited-Phone#159]
Hi there,

I have installed the latest gcphone version on mij Windows based GTA server.

I have downloaded the 1.1 version from this link:
[https://github.com/Re-Ignited-Development/Re-Ignited-Phone/releases/tag/V1.5](url)

My es_extended resource file says that I need the 1.1:
```
description 'ES Extended'

version '1.1.0'
```
After that I downloaded screenshot basis from this link:
[https://github.com/citizenfx/screenshot-basic](url)
Just put that in the resource folder and added it in to the config.cfg just like gcphone. (gcphone before all the esx jobs).

```
ensure gcphone
ensure screenshot-basic
```

The phone works. Only the camera part isn't working. I get no errors in the F8 menu or in de Live Console from the server. 

When using the phone in Twitter I can't get out of the camera app when clicking "Left mouse" or "ENTER" it looks like its making a picture but nothing happens and I can't get out with "Right mouse" or "ESCAPE". So need to restart the gcphone resource to get out of the camera lock.

When using the camera app I can left click and then right click and am back. But also nothing happens.

I also done the following steps to use the webhook for posting the fotos:
[https://github.com/Re-Ignited-Development/Re-Ignited-Phone/issues/154#issuecomment-925549923](url)

```
  "//": "REQUIRES https://github.com/citizenfx/screenshot-basic otherwise set enableTakePhoto to false. Thanks to @GLDmACK for his Upload Service!!!", 
  "enableTakePhoto": true,
  "fileUploadService_Url": "https://discord.com/api/webhooks/xxxxxxxxxxxxx/xxxxxxxxxxx-xxxxxxxxxxxxxxxxx",
  "fileUploadService_Field": "image",
```

GPS:
Is it possible to automatically add the GPS location when people are sending a message to Police, Ambulance and Mechanic?

I see there is code in de addongcphone script but its not working. You only get the Number and the text. What needs to be changed?

Secondly I noticed when using the “GPS Live Location” feature you get a marker on yourselve. Not the person who is sending the message. Makes its not so usefull…

Greetings!

**Comment by ThatPool** [comment]
Hey so about the photo. If you take any photo, it will first upload that photo to your discord channel. Are you able to see any pictures on your discord channel?

**Comment by Brutuss** [comment]
No nothing in the discord channel. I rebuild that channel and made a webhook twice now but nothing in the channel.

**Comment by ThatPool** [comment]
you should try print logs to confirm if it is going through the functions in the start and end in the gcphone 's "exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)" code and in screenshot basic 's requestScreenshotUpload function. And make sure that the webhook is going there correctly, print the url too

```
exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
        print(data.url) --<<<<<-------PRINT HERE--------------------------------
        local resp = json.decode(data)
        DestroyMobilePhone()
        CellCamActivate(false, false)
        --cb(json.encode({ url = resp.files[1].url }))   
        cb(json.encode({ url = resp.attachments[1].proxy_url }))
end)
```

**Comment by Brutuss** [comment]
First off all thnx for helping me out! In the client.lua i've put the "print(data.url)" before the exports as you mentioned above. 

But I can't find the needed file to edit de "requestScreenshotUpload function" in screenshot-basic. 

When I'm home from work i'll test the print output from the gcphone.

**Comment by ThatPool** [comment]
no worries. You'll find the following code in screenshot-basics/src/client/client.ts

(you use console.log to print stuff in typescript and javascript files)
```
exp('requestScreenshotUpload', (url: string, field: string, options: any, cb: (result: string) => void) => {
    const realOptions = (cb !== undefined) ? options : {
        encoding: 'jpg',
        headers: {},
        crop: false
    };

    const realCb = (cb !== undefined) ? cb : options;

    realOptions.targetURL = url;
    realOptions.targetField = field;
    realOptions.resultURL = `http://${GetCurrentResourceName()}/screenshot_created`;
    
    realOptions.correlation = registerCorrelation(realCb);

    SendNuiMessage(JSON.stringify({
        request: realOptions
    }));
});
```

**Comment by Brutuss** [comment]
@thatpool I restarted the server. Logged in to my server en tested the phone with de camera app and the message app. Both generate nothing in de Live Console of my server. :(

**Comment by ThatPool** [comment]
it shouldnt. it is client logs so it will appear on f8 probably

**Comment by Brutuss** [comment]
In F8 it prints my discord webhook now. It prints every first time when taking a picture.

**Comment by ThatPool** [comment]
did you put prints in screenshot basic too? and in twitter when it takes screenshot, put print under CellCamActivate(false, false) like
`print("took screenshot")`

and then under it, 

put
`for k,v in pairs(resp) do print(k,v) if type(v) == "table" then for i,j in pairs(v) do print(i,j) end end end`

send the prints if you can and replace any sensetive information like webhook to "sensetive_info" or something so it doesnt get leaked

**Comment by Brutuss** [comment]
I did't put prints in screenshot because I don't know where to put the console.log command. :( What I did notice is a differents in code whith your posted code. You have some extra code under "encoding: 'jpg' ": 

```
exp('requestScreenshotUpload', (url: string, field: string, options: any, cb: (result: string) => void) => {
    const realOptions = (cb !== undefined) ? options : {
        encoding: 'jpg'
    };

    const realCb = (cb !== undefined) ? cb : options;

    realOptions.targetURL = url;
    realOptions.targetField = field;
    realOptions.resultURL = `http://${GetCurrentResourceName()}/screenshot_created`;
    
    realOptions.correlation = registerCorrelation(realCb);

    SendNuiMessage(JSON.stringify({
        request: realOptions
    }));
});
```
In the gcphone\client\client.lua I have now this code: 

```
elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
	print(data.url)
	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
		local resp = json.decode(data)
		DestroyMobilePhone()
		CellCamActivate(false, false)
		print("took screenshot")
                for k,v in pairs(resp) do print(k,v) if type(v) == "table" then for i,j in pairs(v) do print(i,j) end end end
        --cb(json.encode({ url = resp.files[1].url }))   
        cb(json.encode({ url = resp.attachments[1].proxy_url }))
		end)
        takePhoto = false
	end 
```

The only thing I notice is the webhook link in F8 but thats from the first print command "print(data.url)" no other prints in live console.

**Comment by Brutuss** [comment]
So i have edited this part to match yours:

```
exp('requestScreenshotUpload', (url: string, field: string, options: any, cb: (result: string) => void) => {
    const realOptions = (cb !== undefined) ? options : {
        encoding: 'jpg',
        headers: {},
        crop: false
    };
```

Now it's  working in messages and Twitter. The normal camera app does nothing. Only animation and thats it.

**Comment by ThatPool** [comment]
I don't think normal camera app does anything for now other than for zooming into something. does the same for me too

**Comment by Brutuss** [comment]
Thnx for your help! I only don't understand why this code is wrong on the Github for Screenshot-basic: 

[https://github.com/citizenfx/screenshot-basic/blob/master/src/client/client.ts](url)

You have any idea about the GPS I mentioned?

**Comment by ThatPool** [comment]
You mean send the gps location with the message or automatically set the location on the map?

**Comment by Brutuss** [comment]
Sending it with the message.

**Comment by ThatPool** [comment]
It is possible and somewhat complicated. If i had time, i would have helped you with that </3. Maybe someone here can help you

But here's the code i would have messed with to make it work like you wanted:

gcphone/client/client.lua

```
RegisterNUICallback('sendMessage', function(data, cb)
  if data.message == '%pos%' then
    local myPos = GetEntityCoords(PlayerPedId())
    data.message = 'GPS: ' .. myPos.x .. ', ' .. myPos.y
    data.gpsData = GetEntityCoords(PlayerPedId())
  end
  TriggerServerEvent('gcPhone:sendMessage', data.phoneNumber, data.message, data.gpsData)
end)
```

gcphone/server/server.lua

```
function addMessage(source, identifier, phone_number, message, gps_data)
    local sourcePlayer = tonumber(source)
    local otherIdentifier = getIdentifierByPhoneNumber(phone_number)
    local myPhone = getNumberPhone(identifier)

    local message = '' .. message ..''
    local isRealtimeGPS = false
    local gpsTimeout = Config.ShareRealtimeGPSDefaultTimeInMs

    if (message == '%posrealtime%') then
        if (gps_data) then
            gpsTimeout = gps_data.time
        end
        local timeInMinutes = ESX.Math.Round( gpsTimeout / 1000 / 60 )
        local timeString = (timeInMinutes == nil) and '' or ' ' .. tostring(timeInMinutes) .. ' min'
        message = 'GPS Live Position:' .. timeString .. ''
        isRealtimeGPS = true
    end

    if (message == '%pos%') then
        message = 'GPS Position: ' .. gps_data.x .. ', ' .. gps_data.y
    end

    if otherIdentifier ~= nil then 
        local tomess = _internalAddMessage(myPhone, phone_number, message, 0)
        getSourceFromIdentifier(otherIdentifier, function (osou)
            local targetPlayer = tonumber(osou)
            if targetPlayer ~= nil then 
                -- TriggerClientEvent("gcPhone:allMessage", osou, getMessages(otherIdentifier))
                if (isRealtimeGPS == true) then
                    TriggerClientEvent('gcPhone:receiveLivePosition', targetPlayer, sourcePlayer, gpsTimeout, myPhone, 0)
                end
                TriggerClientEvent("gcPhone:receiveMessage", targetPlayer, tomess)
            end
        end) 
    end
    local memess = _internalAddMessage(phone_number, myPhone, message, 1)
    TriggerClientEvent("gcPhone:receiveMessage", sourcePlayer, memess)
end
```

check for the phone number player is messaging to and if the number is 'police' 'ambulance' or 'mechanic', add his message with his gps coords to the message
![image](https://user-images.githubusercontent.com/63418483/135751595-67ce5c33-e245-4dd9-962a-974ba604a320.png)
