### ISSUE TITLE
Twitter notifications

### ISSUE THREAD

**Issue by gorerdrew** [Re-Ignited-Development/Re-Ignited-Phone#16]
not necessarily an issue but i was wondering if the twitter app could give some kind of notification

**Comment by RockySouthpaw** [comment]
It does

**Comment by RockySouthpaw** [comment]
![ZkItpfDYE7](https://user-images.githubusercontent.com/55056068/90578159-9afc7d00-e190-11ea-9423-8234daf819e5.png)
Just need to enable it in settings.

**Comment by BTNGaming** [comment]
By default you only get notified if you are "Mentioned". If this is still an issue for you, and you can't get notifications to work, please open up an issue again and i'll take a look for you.
