### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token (vendor.js:6) and Uncaught TypeError: Cannot read property 'call' of undefined (manifest.js:1)

### ISSUE THREAD

**Issue by blaqqendwhyt** [Re-Ignited-Development/Re-Ignited-Phone#163]
Hello,

Since manyh month we used the phone, and work perfectly.

But since yesterday we have this strange error, and we don't understand why...

Does it call something non internal that have died ?

Thanks for the help :)

![image](https://user-images.githubusercontent.com/57453491/136984888-dd52a21e-8075-41dc-add7-6954ad1cc38a.png)

**Comment by Dallepower** [comment]
Did you by any chance get this fixed? I'm having the same error... and suddenly i can't open the phone anymore, i've even tried it on a fresh esx installed server :(
