### ISSUE TITLE
Pictures are black

### ISSUE THREAD

**Issue by FakeItalianMan** [Re-Ignited-Development/Re-Ignited-Phone#167]
I take a picture but it's just black, Any suggestions on how to fix that?

**Comment by FakeItalianMan** [comment]
Now it just doesn't work at all. It gets stuck in the take picture animation and doesn't take the picture?

**Comment by kagesamo** [comment]
Do you have the resource 'screenshot-basic'?

**Comment by FakeItalianMan** [comment]
> Do you have the resource 'screenshot-basic'?

Yes

**Comment by BTNGaming** [comment]
Did you change the screenshot config since the default one doesn't work?
