### ISSUE TITLE
gcphone doesn't give phone number

### ISSUE THREAD

**Issue by nuageee** [Re-Ignited-Development/Re-Ignited-Phone#179]
Hello, i just install gcphone and i got an error:
the phone doesn't give any phone number just ###-####

im using esx-legacy si if you know how to solve this,

**Comment by shaundepaul15** [comment]
same here. i am having the same issues.

**Comment by BTNGaming** [comment]
You installed the wrong version of the phone. Download it from the Releases tab directly, NOT the github resource.
