### ISSUE TITLE
Does the Phone not work with SaltyChat ?

### ISSUE THREAD

**Issue by KlosteinRaucher** [Re-Ignited-Development/Re-Ignited-Phone#181]
Hey, i dont know, how to setup the phone, so you can use it to call someone over SaltyChat. Is that even possible, and if not, how make i calls work ?

**Comment by Marc85BPG** [comment]
it works, but not client side - you have to make changes in server.lua
like this 
https://i.imgur.com/LvYxgx8.jpg
