### ISSUE TITLE
calling does not work

### ISSUE THREAD

**Issue by JeffreyGerritsen** [Re-Ignited-Development/Re-Ignited-Phone#184]
I'm running on ESX legacy, got the messages to emergency services working after many attempts. It's just not possible to call each other. Notification not received. No errors in console or f8

Can someone help me with this?

**Comment by karovx** [comment]
I am still having this problem and cannot get it fixed no matter what phone I tried, can someone help?

**Comment by wil2005-development** [comment]
I have the same problem. I currently searching through the files to see if i see the problem.

**Comment by BTNGaming** [comment]
Do you have it setup for the proper voice system? I have it in my dev server and it works flawlessly, both onesync legacy and infinity. I'm on the most up to date version of ESX (ES_Extended)

**Comment by BTNGaming** [comment]
Also make sure you download from RELEASES not from the main github branch.
