### ISSUE TITLE
Crash when using camara

### ISSUE THREAD

**Issue by sorenmarquardt** [Re-Ignited-Development/Re-Ignited-Phone#24]
Hi my phone crashes when i use,
send phote or,
change avatar camara

![28034eb2f35ea3d50769ee2bd1d29d24](https://user-images.githubusercontent.com/10225477/91565345-5ae08b80-e942-11ea-88d4-f2dd056d595e.png)

**Comment by gabrielcalderon** [comment]
@sorenmarquardt Did you install the screenshot-basic resource?

**Comment by sorenmarquardt** [comment]
i have now :) thanks
