### ISSUE TITLE
Incoming call showing UNKNOWN

### ISSUE THREAD

**Issue by argykaraz** [Re-Ignited-Development/Re-Ignited-Phone#27]
When receiving a call, (and have the contact in your contacts list) the display shows "Unknown". In your app.js has the value "APP_PHONE_NUMBER_UNKNOWN".
It should show the callers name, but I couldnt figure out what to replace it with.

**Comment by RockySouthpaw** [comment]
So just to clarify for repro:
1. Add contact to phone.
2. Receive call from said contact
3. Contact shows as unknown

right?

**Comment by argykaraz** [comment]
Exactly. Thank you for the quick reply.

**Comment by RockySouthpaw** [comment]
Okay ill add it to the trello and look for a fix.

**Comment by RockySouthpaw** [comment]
Has been added to the trello. https://trello.com/c/GEvA6szW/58-call-shows-up-as-unknown

**Comment by BTNGaming** [comment]
Is this always occurring or only when you hit Cqll Anonymously

**Comment by argykaraz** [comment]
> Is this always occurring or only when you hit Cqll Anonymously

We didnt use call anonymously in our test. What was supposed to happen, was to see the callers name and the number, but instead it showed the number, with the text "Unknown".

To clarify:
- Add a new contact, with number and name.
- Have the contact call you.
What should happen:
See the number and the name you added in the contacts.
What really happens:
It shows the number, but the name says "Unknown".
