### ISSUE TITLE
When sending "GPS Coordinates" to any job, the cords are returned to as %pos% & new_banking transfers doesn't work.

### ISSUE THREAD

**Issue by NoobyTubezz** [Re-Ignited-Development/Re-Ignited-Phone#30]
Hola amigos, 

When our players request a mechanic the mechs receive this;
![image](https://user-images.githubusercontent.com/6962192/92894568-9daa6500-f412-11ea-9774-f29bab56dd86.png)

Also, issue with bank transferring, we obviously use new_banking but when people send money to each other it just doesn't send, no error, no notifications or anything

**Comment by RockySouthpaw** [comment]
What es_extended are you on?

**Comment by yagizher** [comment]
Couldn't reproduce

**Comment by RockySouthpaw** [comment]
I’ve yet to be able to reproduce this as well.

**Comment by RockySouthpaw** [comment]
Reproduced the issue.

!. Open contacts app
2. Click on police
3. Send gps position
Shows up as `From PHONENUMBER : %pos%

**Comment by Racpy** [comment]
share Realtime Position to job have problem too. if i want share 5 mins . it still share 1 min on map

**Comment by RockySouthpaw** [comment]
@Racpy Open a separate issue. 

@NoobyTubezz Please open a separate issue for the newbanking issue.
