### ISSUE TITLE
When adding a contact from recent calls, it goes to home screen and throws a database error.

### ISSUE THREAD

**Issue by RockySouthpaw** [Re-Ignited-Development/Re-Ignited-Phone#32]
1. Open phone
2. Open Phone App
3. Navigate to contacts and dial a number.
4. End the call.
5. Go to recent calls and right click on new contact. (Same occurs with key control.)
6. Phone will go to home screen.

This results in this error:
```
[ERROR] [MySQL] [gcphone] An error happens on MySQL for query "INSERT INTO phone_users_contacts (`identifier`, `number`,`display`) VALUES('steam:110000112964a88', @number, @display)": ER_BAD_NULL_ERROR: Column 'display' cannot be null
````

You can also achieve this by trying to add to contacts an existing contact.

**Comment by Archangelza1** [comment]
To Fix This You Can Make A Modal Using The Following

Add in AppelsRecents

`save (numero) {
      if (this.id !== -1) {
        Modal.CreateTextModal({
          title: this.IntlString('APP_PHONE_ENTER_NAME'),
          limit: 12
        }).then(data => {
          this.addContact({
            display: data.text,
            number: numero
          })
        })
      } else {
        console.log('No añadido')
      }
    },`

And add that locale to the config.json

**Comment by RockySouthpaw** [comment]
> To Fix This You Can Make A Modal Using The Following
> 
> Add in AppelsRecents
> 
> `save (numero) { if (this.id !== -1) { Modal.CreateTextModal({ title: this.IntlString('APP_PHONE_ENTER_NAME'), limit: 12 }).then(data => { this.addContact({ display: data.text, number: numero }) }) } else { console.log('No añadido') } },`
> 
> And add that locale to the config.json

Can you PR this?

**Comment by TasoOneAsia** [comment]
Make sure that PR also has that formatted correctly please.

**Comment by Archangelza1** [comment]
Will do
