### ISSUE TITLE
Gcphone photo notification

### ISSUE THREAD

**Issue by diepmiho** [Re-Ignited-Development/Re-Ignited-Phone#35]
Hello so im new in this kind of thing, i actually don't have any experience in scripting. 
My photo notification only shows the URL i dont know if it because of a screenshot basic or in phone.

**Comment by RockySouthpaw** [comment]
Added  to trello awhile ago. Image looks as such
![HftsFsmXjc](https://user-images.githubusercontent.com/55056068/94321344-47363e00-ff5d-11ea-8081-9a557679dd51.png)
