### ISSUE TITLE
Random spawn

### ISSUE THREAD

**Issue by Toxicnono** [Re-Ignited-Development/Re-Ignited-Phone#36]
The phone work great but when i'm connect on the server i spawn in random place. When i desactivate the phone in the server.cfg, i spawn in my last place.

**Comment by RockySouthpaw** [comment]
I don’t see how this can be caused by the phone. 

What es_extended? What’s the start order?

**Comment by Toxicnono** [comment]
It's es_extended final and i respect the start order with jobs:

ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

############ DATABASE ############
set mysql_connection_string "user=root;database=rpacademy;localAddress=127.0.0.1"
set es_enableCustomData 1

add_principal group.admin group.user
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow

############ LIBS ############
ensure mysql-async
ensure es_extended

############ ESX ############
ensure esx_menu_default
ensure esx_menu_list
ensure esx_menu_dialog
ensure esx_addonaccount
ensure esx_basicneeds
ensure esx_society
ensure esx_status
ensure trew_hud_ui
ensure esx_inventoryhud
ensure new_banking
ensure esx_skin
ensure skinchanger
ensure nicoo_charcreator
ensure esx_identity
ensure esx_addoninventory
ensure esx_datastore
ensure esx_billing
ensure esx_vehicleshop
ensure esx_shops

############ COM ############
ensure gcphone
ensure mumble-voip
ensure rp-radio

############ ESX JOB ############
ensure esx_ambulancejob

############ BASE ############
ensure vMenu
ensure pNotify

############ MAP ############
ensure map
ensure streetLabel
ensure nearest-postal

**Comment by RockySouthpaw** [comment]
Did you download the correct version from the release tab?

**Comment by Toxicnono** [comment]
Yes, and i try again, it's the same issue

**Comment by RockySouthpaw** [comment]
Apparently the issue is caused by you having spawnmanager and mapmanager as 1.2 ditches these.
