### ISSUE TITLE
Dialog doesn't show up.

### ISSUE THREAD

**Issue by Kasp09** [Re-Ignited-Development/Re-Ignited-Phone#37]
When going to phone -> favorites -> And i try to message any police job i do not get any dialog to literally text police, mechanic and ambulance service, when i do it through contacts, messages it doesn't go through.

**Comment by RockySouthpaw** [comment]
Added to trello. 

Repo:

1. Open Phone App
2. Go to favorites
3. Click on police
4. Click on send message
5. Phone goes to home screen, text box remains.

(Tested with both Keyboard and Mouse control)
