### ISSUE TITLE
Emergency Services not recieving notifications from a text

### ISSUE THREAD

**Issue by 1F1SH1** [Re-Ignited-Development/Re-Ignited-Phone#41]
Emergency Services not recieving notifications from a text the dialog box shows up i type something in but they dont recieve a notification and I have been trying to figure this out for weeks. I am getting a code in the console saying 
=warning = Trying to call an unregistered service => numero : police
=warning = Trying to call an unregistered service => numero : ambulance

or any service i try and message

Any help is much appreciated

**Comment by RockySouthpaw** [comment]
Do you have esx_policejob

**Comment by 1F1SH1** [comment]
Hello yes I do. Managed to get it working don’t know how if I’m completely honest but that’s for you help anyway haha
