### ISSUE TITLE
Suggestion: Apps

### ISSUE THREAD

**Issue by NoobyTubezz** [Re-Ignited-Development/Re-Ignited-Phone#42]
I think google maps could be a cool app on the phone? Could be good for those who don't have the minimap showing constantly.

**Comment by Oldarorn** [comment]
https://github.com/Re-Ignited-Development/Re-Ignited-Phone/issues/4

you have to write your suggestions here

**Comment by NoobyTubezz** [comment]
> #4
> 
> you have to write your suggestions here

Ah shit, sorry hun

**Comment by RockySouthpaw** [comment]
Please post it in https://github.com/Re-Ignited-Development/Re-Ignited-Phone/issues/4

Its actually a cool suggestion tbh.
