### ISSUE TITLE
Discord logs 

### ISSUE THREAD

**Issue by diepmiho** [Re-Ignited-Development/Re-Ignited-Phone#47]
Discord logs not working for me I double check the url for my discord but it is still now showing

**Comment by RockySouthpaw** [comment]
We implemented discord logging? Thought it was part of a PR and not added? https://github.com/Re-Ignited-Development/Re-Ignited-Phone/pull/46

**Comment by diepmiho** [comment]
Ohh sorry I didnt know that ty
