### ISSUE TITLE
phone nui blocking input while open

### ISSUE THREAD

**Issue by Developer-Bear** [Re-Ignited-Development/Re-Ignited-Phone#48]
Unable to use controls (such as N for speaking) while the phone is out

**Comment by itschip** [comment]
Are you using the mouse or the keyboard to use navigate in the phone?

**Comment by Developer-Bear** [comment]
Mouse Input, with keyboard input it works fine.

**Comment by itschip** [comment]
@Developer-Bear so when you choose mouse control `SetNuiFocus` is set to true on both `hasFocus` and `hasCursor`. This meaning that everything you do basically is in the NUI, so there is no way to interact with other ingame functions. Other than whats within the current NUI.
