### ISSUE TITLE
inserting numbers

### ISSUE THREAD

**Issue by P0Xyio** [Re-Ignited-Development/Re-Ignited-Phone#51]
When trying to insert numbers, I receive error.
Happens in bank/adding contact/twitter
![unknown (3)](https://user-images.githubusercontent.com/58112474/95803121-358fbd00-0cf7-11eb-854a-a5b34256e24a.png)

**Comment by RockySouthpaw** [comment]
Did adding tostring() fix the issue?

**Comment by P0Xyio** [comment]
yes

**Comment by RockySouthpaw** [comment]
![](https://cdn.discordapp.com/attachments/719393533131489301/765375232369491968/unknown.png)
Will apply next release

**Comment by RockySouthpaw** [comment]
Applied on latest release.
