### ISSUE TITLE
dead people GPS problem 

### ISSUE THREAD

**Issue by bashon1** [Re-Ignited-Development/Re-Ignited-Phone#53]
dead people GPS problem 
when someone Dead and press G to send gps to ambulance they dont get anything
am using 1.2 final

**Comment by bashon1** [comment]
if a person dies we hit G to send the distress signal but the ambulance staff are not getting the notification.

**Comment by RockySouthpaw** [comment]
Are you using latest ambulance job

**Comment by bashon1** [comment]
> Are you using latest ambulance job

Yes i use last version 
https://github.com/esx-framework/esx_ambulancejob

**Comment by JSanchezFDZ** [comment]
I have same issue

**Comment by RockySouthpaw** [comment]
Are you also on 1.2?

The issue isn’t prevalent on 1.1 so I can’t reproduce the issue. Can you guys add some prints to see exactly what’s being triggered?

**Comment by bashon1** [comment]
i can not do it, 
if you can fix it for final version extended

**Comment by FBFezz** [comment]
Its an issue with esx_Ambulancejob. I made a pr on there but not too sure if it does fix it but It worked for me

**Comment by bashon1** [comment]
anyway to fix it? or which ambulance job work with it?

**Comment by Ivannnmmn** [comment]
This seems to be a problem with "esx_ambulancejob".
This should solve your problem
Find
`
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords = GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_ambulancejob:onPlayerDistress')
end
`

replace
`
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords = GetEntityCoords(playerPed)
	local id = GetPlayerServerId(PlayerId())
	local PlayerCoords = { x = coords.x, y = coords.y, z = coords.z }
	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_ambulancejob:onPlayerDistress')
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', 'Player ID: '.. id ..' Need medical assistance.', PlayerCoords, {
		PlayerCoords = { x = coords.x, y = coords.y, z = coords.z },
	})
end
`
Please tell me if it works or can't

**Comment by LillefixHD** [comment]
> This seems to be a problem with "esx_ambulancejob".
> This should solve your problem
> Find
> 
> `function SendDistressSignal()
> local playerPed = PlayerPedId()
> local coords = GetEntityCoords(playerPed)
> 
> ```
> ESX.ShowNotification(_U('distress_sent'))
> TriggerServerEvent('esx_ambulancejob:onPlayerDistress')
> ```
> 
> end`
> 
> replace
> 
> `function SendDistressSignal() local playerPed = PlayerPedId() local coords = GetEntityCoords(playerPed) local id = GetPlayerServerId(PlayerId()) local PlayerCoords = { x = coords.x, y = coords.y, z = coords.z } ESX.ShowNotification(_U('distress_sent')) TriggerServerEvent('esx_ambulancejob:onPlayerDistress') TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', 'Player ID: '.. id ..' Need medical assistance.', PlayerCoords, { PlayerCoords = { x = coords.x, y = coords.y, z = coords.z }, }) end`
> Please tell me if it works or can't

I can confirm that this code solved the issue

**Comment by Gameadictive** [comment]
Is not working for me
