### ISSUE TITLE
No Phone Number

### ISSUE THREAD

**Issue by hectorfrs** [Re-Ignited-Development/Re-Ignited-Phone#54]
I have a situation, the phone numbers are not assigned to the users. Appears blank and the phone without number is not functional. I will appreciate the help. Thanks

Other problem:
SCRIPT ERROR: @gcphone/server/esxaddonsgcphone-s.lua:24: attempt to concatenate a nil value (field 'numero')
> notifyAlertSMS (@gcphone/server/esxaddonsgcphone-s.lua:24)
> callback (@gcphone/server/esxaddonsgcphone-s.lua:94)
> ref (@gcphone/server/esxaddonsgcphone-s.lua:143)
>  (@mysql-async/mysql-async.js:15543)

**Comment by RockySouthpaw** [comment]
What esx are you on? Did you do a fresh install of the phone?

**Comment by hectorfrs** [comment]
Hi,

ESX Version 1.1

The installation is a new one, on a new server. The installation was done as recommended.

**Comment by hectorfrs** [comment]
[https://cdn.discordapp.com/attachments/733810625808957470/767872645906694144/unknown.png](url)

**Comment by hectorfrs** [comment]
Good morning. Any ideas on how to proceed?

**Comment by RockySouthpaw** [comment]
I don’t use Maria DB but @itschip might know.

Can you post the full error please without being cropped partially. Did you also make any changes to phone numbers?

**Comment by hectorfrs** [comment]
For the moment it would be working with the assignment of the telephone number. The system is not generating it. Not assigning anything keeps the field NULL.

The configuration is as follows.

   "useFormatNumberFrance": false,


**config.lua**

Config.newESX = false -- True = ESX 1.2(v1final), False = ESX 1.1 and older. (NOT WORKING YET, FORGOT SOMETHING IN CODE, HAVE TO FIND IT)

Config.KeyOpenClose = 288 -- F1
Config.KeyTakeCall  = 38  -- E

Config.UseMumbleVoIP = true -- Use Frazzle's Mumble-VoIP Resource (Recommended!) https://github.com/FrazzIe/mumble-voip
Config.UseTokoVoIP   = false

**Comment by itschip** [comment]
Did you install the sql queries? Because I guess your are getting the `###-####` instead of the actual number?

**Comment by hectorfrs** [comment]
Correct, the sql queries were installed. Something is not running for me to assign the random numbers. something is not recognizing. I don't know where or what it might be.

**Comment by itschip** [comment]
And you downloaded the correct .zip file from releases?
Or took the `server.lua` from the `server-1-1` or whatever its called when you are called.

**Comment by hectorfrs** [comment]
The download, I understand that it was correct.

https://github.com/Re-Ignited-Development/Re-Ignited-Phone/releases/download/V1.3/resources-1.1.zip

**Comment by itschip** [comment]
Alright, so that is atleast correct. Which version of MariaDB do you have?

**Comment by hectorfrs** [comment]
[root@ALDEA ~]# mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 70338
Server version: **10.4.12-MariaDB MariaDB Server**

**Comment by hectorfrs** [comment]
What criteria does the script take into consideration to create the phone number and assign it?

I have this character creator that makes changes to the identifier.

https://modit.store/products/mf-multicharacter?variant=33078709026893

**Comment by RockySouthpaw** [comment]
I doubt it has anything to do with it but if it did you couldn’t make any changes since the source code isn’t provided. 

Did you try any other phones?

**Comment by hectorfrs** [comment]
Don't worry, I'm not asking, I'm just asking because it changes the identity by removing the word "steam".

I had a previous version of the gcphone, but I upgraded to this version of you.

**Comment by MarceRewell** [comment]
> For the moment it would be working with the assignment of the telephone number. The system is not generating it. Not assigning anything keeps the field NULL.
> 
> The configuration is as follows.
> 
> "useFormatNumberFrance": false,
> 
> **config.lua**
> 
> Config.newESX = false -- True = ESX 1.2(v1final), False = ESX 1.1 and older. (NOT WORKING YET, FORGOT SOMETHING IN CODE, HAVE TO FIND IT)
> 
> Config.KeyOpenClose = 288 -- F1
> Config.KeyTakeCall = 38 -- E
> 
> Config.UseMumbleVoIP = true -- Use Frazzle's Mumble-VoIP Resource (Recommended!) https://github.com/FrazzIe/mumble-voip
> Config.UseTokoVoIP = false

I had that problem and my solution for that was edit server.lua and find a value "mun" and change for "num", after that the phone numbers be assigned with normality in the DB, hope can help and u can resolve ur issue. kind regards
