### ISSUE TITLE
Phone UI Not opening 

### ISSUE THREAD

**Issue by WindiestHook381** [Re-Ignited-Development/Re-Ignited-Phone#56]
Press F1, animation appears but no ui. No errors.

**Comment by RockySouthpaw** [comment]
Did you download it from the release tab?

**Comment by WindiestHook381** [comment]
Yes

**Comment by WindiestHook381** [comment]
All fixed. I changed on of my other things which was interferring.

**Comment by TsShoyu** [comment]
Hi, i'm having the same problem, do you remember what did you do to make it work?
