### ISSUE TITLE
Can't add new phone numbers starting with a zero.

### ISSUE THREAD

**Issue by Shiinuu** [Re-Ignited-Development/Re-Ignited-Phone#57]
I am using the "french" phone numbers, and while trying to add one of these phone numbers to my contacts, it is just not possible. Whenever i type 06....... , the 0 at the start just disappears.

I have added  tostring(text) into the code as mentioned in a different issue, because i could not type only numbers, had to type atleast 1 letter with the number in the phone, for let's say transferring money via the bank.

**Comment by RockySouthpaw** [comment]
So this was reported in the discord as well. Seems to be just the contact app. 

What’s the exact code for the number format?

**Comment by RockySouthpaw** [comment]
Change this:
```lua
math.randomseed(os.time()) 

--- For phone number style XXX-XXXX
function getPhoneRandomNumber()
    local numBase0 = math.random(100,999)
    local numBase1 = math.random(0,9999)
    local num = string.format("%03d-%04d", numBase0, numBase1)

    return num
end

--- For this style 06XXXXXXXX Remove the -- from the next 3 lines
-- function getPhoneRandomNumber()
--     return '0' .. math.random(600000000,699999999)
-- end
```

To this
```lua
math.randomseed(os.time()) 

--- For phone number style XXX-XXXX
-- function getPhoneRandomNumber()
--     local numBase0 = math.random(100,999)
--     local numBase1 = math.random(0,9999)
--     local num = string.format("%03d-%04d", numBase0, numBase1)

--     return num
-- end

--- For this style 06XXXXXXXX Remove the -- from the next 3 lines
function getPhoneRandomNumber()
    return '0' .. math.random(860000000,869999999)
end
```

Does this help you at all?

**Comment by fucekar** [comment]
I Have same but i dont use this type number

**Comment by fucekar** [comment]
math.randomseed(os.time())

pre_numbers = {
	"0912",
	"0915",
	"0910",
	"0919",
	"0935",
	"0939",
	"0936",
	"0933",
	"0931",
	"0990",
	"0998"
}

--- For this style 06XXXXXXXX Remove the -- from the next 3 lines
-- function getPhoneRandomNumber()
--     return '0' .. math.random(600000000,699999999)
-- end

function getPhoneRandomNumber()
	local ran_pre = math.random(1, #pre_numbers)
	local number = (pre_numbers[ran_pre])..(math.random(1000000, 9999999))
	return number
end

**Comment by fucekar** [comment]
i want zero (0) i just want i can write 0 in new contact page , what i do?
