### ISSUE TITLE
Can't make camera working

### ISSUE THREAD

**Issue by bertusdev** [Re-Ignited-Development/Re-Ignited-Phone#59]
hey!
I've installed everything, and the photos made from twitter f.e are being sent and stored to the server, but it's not showing on the twitter profile.
Same happens when sending a picture to a message, it doesn't send. No notification, no callback.
Any idea?

**Comment by RockySouthpaw** [comment]
You have screenshot basic?

**Comment by bertusdev** [comment]
Yes.
