### ISSUE TITLE
infoCall error

### ISSUE THREAD

**Issue by xrtw** [Re-Ignited-Development/Re-Ignited-Phone#61]
https://i.gyazo.com/a6dfd6afe3f215ce4cdf6ca7701b2f13.png 

> RegisterServerEvent('gcPhone:acceptCall')
> AddEventHandler('gcPhone:acceptCall', function(infoCall, rtcAnswer)
>     local id = **infoCall**.id
>     if AppelsEnCours[id] ~= nil then
>         if PhoneFixeInfo[id] ~= nil then
>             onAcceptFixePhone(source, infoCall, rtcAnswer)
>             return
>         end
>         AppelsEnCours[id].receiver_src = infoCall.receiver_src or AppelsEnCours[id].receiver_src
>         if AppelsEnCours[id].transmitter_src ~= nil and AppelsEnCours[id].receiver_src~= nil then
>             AppelsEnCours[id].is_accepts = true
>             AppelsEnCours[id].rtcAnswer = rtcAnswer
>             TriggerClientEvent('gcPhone:acceptCall', AppelsEnCours[id].transmitter_src, AppelsEnCours[id], true)
> 			SetTimeout(1000, function() -- change to +1000, if necessary.
>        		TriggerClientEvent('gcPhone:acceptCall', AppelsEnCours[id].receiver_src, AppelsEnCours[id], false)
> 	    end)
>             saveAppels(AppelsEnCours[id])
>         end
>     end
> end)

**Comment by RockySouthpaw** [comment]
Are you using mumble?

**Comment by xrtw** [comment]
yes

**Comment by RockySouthpaw** [comment]
Did you turn it to true in the config to use mumble?

**Comment by xrtw** [comment]
of course i did.

**Comment by RockySouthpaw** [comment]
Did you ever solve the issue?
