### ISSUE TITLE
if you dont have phone, player can still call you

### ISSUE THREAD

**Issue by xrtw** [Re-Ignited-Development/Re-Ignited-Phone#63]
if you dont have in your inventory phone and player calls you, you can hear telephone ringing.. so annoying when you cant stop that call.. probably its fixable

**Comment by RockySouthpaw** [comment]
Should be an easy fix

**Comment by RockySouthpaw** [comment]
On trello. Looks like its below `if inRangeToActivePhone == true and currentPlaySound == false then`

**Comment by RockySouthpaw** [comment]
Fixed and will be in next release.
