### ISSUE TITLE
Error in F8 menu when sending a messages to jobs

### ISSUE THREAD

**Issue by gamenhaadee** [Re-Ignited-Development/Re-Ignited-Phone#68]
![image](https://user-images.githubusercontent.com/33785074/99148032-c86ca000-2685-11eb-843e-359e27b34f13.png)

i get this error everytime someone wants to send to messages.

is there a fix for it?

**Comment by RockySouthpaw** [comment]
what esx

**Comment by RockySouthpaw** [comment]
✋Hey there!

Thanks for the report, but it appears we may need more information from you regarding the issue! Please fill out this template so we can better assist you with your issue.

**Version Information (What release are you using): **

**What version of the ESX Framework are you running?**

**Is this issue related to connectivity to a resource outside of Reignited Phone?**
