### ISSUE TITLE
Using payphone when in car - causes graphics to drop

### ISSUE THREAD

**Issue by ksduster** [Re-Ignited-Development/Re-Ignited-Phone#73]
When using a payphone while in a car, after the call is completed and you start to drive away - the graphics go haywire/bad until you exit the vehicle.
This is for vanilla and add-on vehicles.

**Comment by RockySouthpaw** [comment]
Can you record a video? 

And PC specs + ESX version?

**Comment by RockySouthpaw** [comment]
Still need this information.

**Comment by ksduster** [comment]
I apologize, Yes I can record a video tomorrow.

**Comment by RockySouthpaw** [comment]
Thanks

**Comment by RockySouthpaw** [comment]
video?

**Comment by RockySouthpaw** [comment]
Okay you haven’t provided any of the requested information so I’m gonna close this.
