### ISSUE TITLE
RECENT CALL LIST ORDER

### ISSUE THREAD

**Issue by akshaygitty** [Re-Ignited-Development/Re-Ignited-Phone#75]
Everything is working fine. A great release. But my RECENT CALL LIST isnt in Order. What should i do to make that in order? Any help?

**Comment by RockySouthpaw** [comment]
What esx version are you using?

**Comment by RockySouthpaw** [comment]
Did you alter the resource any? And can you also post a screenshot of the issue so I can add it to trello?

**Comment by akshaygitty** [comment]
> What esx version are you using?

We are using 1.1

**Comment by akshaygitty** [comment]
> Did you alter the resource any? And can you also post a screenshot of the issue so I can add it to trello?

We just customized the phone and nothing altered with the code.

**Comment by akshaygitty** [comment]
![Screenshot (325)](https://user-images.githubusercontent.com/70011760/100547315-260b0a00-328c-11eb-9051-82663f58c935.png)

So here in screenshot The call list isnt in order. Call i made a minute ago is shown as 21hours ago.. And call made 6hourse ago is below the 21hours one. I donno why this happens.
