### ISSUE TITLE
Double Notification 

### ISSUE THREAD

**Issue by guccistre** [Re-Ignited-Development/Re-Ignited-Phone#76]
multiple notifications message when you have saved a contact, the notifications is the number and name of the contact.
use mythic_notify

**Comment by TasoOneAsia** [comment]
✋Hey there!

Thanks for the report, but it appears we may need more information from you regarding the issue! Please fill out this template so we can better assist you with your issue.

**Version Information (what release are you using): **

**What version of the ESX Framework are you running?**

**Is this issue related to connectivity to a resource outside of Reignited Phone?**

**Comment by RockySouthpaw** [comment]
This phone doesn't even use mythic for anything so what are you even talking about?

**Comment by guccistre** [comment]
![20201204062736_1](https://user-images.githubusercontent.com/72303359/101101029-37407780-35fa-11eb-8219-ee7086bdefad.jpg)
When I save a contact, and I try to send a message, the notification double (phone number and name contact)

**Comment by TasoOneAsia** [comment]
We don't utilize mythic notify in the slightest.

**Comment by guccistre** [comment]
> We don't utilize mythic notify in the slightest.

yes I changed it using mythic notify, but it's the same if using esx notification

**Comment by RockySouthpaw** [comment]
We would need to know what line you're refering to

**Comment by guccistre** [comment]
client.lua, (gcphone:receivemessage)

**Comment by TasoOneAsia** [comment]
Ok, if you can replicate this behavior without modifying the code. Then make another issue. We do not support resources that are altered.
