### ISSUE TITLE
More of a help Really... Can't get the builds running.

### ISSUE THREAD

**Issue by WindiestHook381** [Re-Ignited-Development/Re-Ignited-Phone#80]
Hi There,

I am trying to run the phone but none of the buttons work when the phone is open. Last time this was because I hadn't run the npm builds but this time I can't seem to set them up properly although somehow I did last time. Don't ask me how.

Don't suppose you could help?

**Comment by TasoOneAsia** [comment]
Are you using the listed releases rather than downloading from source? The release are already packed/built meaning you do not have to build the phone yourself. It should just work.

**Comment by WindiestHook381** [comment]
I am yes. The time before I did the npm install and that malarkey which then worked. It comes up but when you click on the apps, it doesn't do anything which was fixed by whatever I did before.

**Comment by TasoOneAsia** [comment]
Reinstall because something is clearly screwed up. Let us know if problems still occur.
