### ISSUE TITLE
they don't receive the phone call

### ISSUE THREAD

**Issue by sflabrie** [Re-Ignited-Development/Re-Ignited-Phone#82]
When we call the other person don't receive the phone call.

I try the version 1.1 and 1.2 and i have the same problem for both version.

Can you help me ? thanks

**Comment by RockySouthpaw** [comment]
Do you have phone as an item enabled/disabled? And 1.1 is for 1.1 ESX. 1.2 is for 1.2 ESX. You need to use the correct one.

**Comment by sflabrie** [comment]
Item is disabled

**Comment by sflabrie** [comment]
We have the phone and when i call someone I see that i do the call... but the other person don't receive the call 

We try if the Text message work between us and it's work

**Comment by RockySouthpaw** [comment]
Can you try the release before the beta?

**Comment by RockySouthpaw** [comment]
And can you state your esx version?

**Comment by sflabrie** [comment]
How to I get my ESX Version ?

**Comment by sflabrie** [comment]
if i do Version on my consol:
 "version" is "FXServer-master v1.0.0.3148 linux"
 default: "FXServer-master v1.0.0.3148 linux"
 type: string

**Comment by sflabrie** [comment]
I tried the version before the Beta, we receive the calls but we can't hear the person

**Comment by RockySouthpaw** [comment]
Open your es_extended fxmanifest or resource.lua and give me the version inside.

And you need mumble to talk to people.

**Comment by sflabrie** [comment]
mumble is active with the last version
I put True for Mumble in the config

For Es_extended the version is 1.1

**Comment by RockySouthpaw** [comment]
I just tried phone calling on ESX 1.1 and it worked fine with the config set to false for item requirement and with it set to true.

Idk if you were dialing the number wrong or what but its not an issue with the resource.

**Comment by sflabrie** [comment]
I take a old version of Mum,ble and right now it's working we hear the other person when we call

**Comment by RockySouthpaw** [comment]
Okay cool. Issue closed then.
