### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by sflabrie** [Re-Ignited-Development/Re-Ignited-Phone#83]
Hi (Again)
The phone number appear xxxxx (only 5 number). What i need to do to have xxx-xxxx

This is what is active in server.lua 
--- For phone numbers like: XXX-XXXX
function getPhoneRandomNumber()
    local numBase0 = math.random(100,999)
    local numBase1 = math.random(0,9999)
    local num = string.format("%03d-%04d", numBase0, numBase1)

	return num
end

and this in the .../[Phone]/gcphone/html/static/config/config.json

  "useFormatNumberFrance": false,

So what i need to do to have the phone number like this xxx-xxxx

thanks

**Comment by RockySouthpaw** [comment]
The phone number is already XXX-XXXX by default?

**Comment by sflabrie** [comment]
That's not work because the phone number that i have right now is  90236 (see Image)

What i need to do to be sure the phone number it's xxx-xxxx.
![20201217112845_1](https://user-images.githubusercontent.com/73554418/102514901-109f2980-405b-11eb-9709-20a3651a5177.jpg)

**Comment by RockySouthpaw** [comment]
This isn’t something wrong with the phone. It’s something you did due to improper installation.

**Comment by sflabrie** [comment]
Okay, but I don't change anything in the phone i only do the installation. 
I don't do any modification in the folder.

I tried to put in France Number and i have the 5 number too.

**Comment by XiosBombay** [comment]
Just install the phone from the releases tab and try it.

**Comment by sflabrie** [comment]
I delete all the file and reinstall everything  and i have the 5 number.
And i change nothing in the file.

**Comment by RockySouthpaw** [comment]
Truncate your tables you made. You must have created them with something else before.

**Comment by sflabrie** [comment]
I do it a clear all the information in my table.
