### ISSUE TITLE
Not receiving calls on ESX 1.1

### ISSUE THREAD

**Issue by Itz-Hyperz** [Re-Ignited-Development/Re-Ignited-Phone#87]
Hi, running into an issue with phone calls, While it rings the contact, it won't actually show on the other persons phone that they are being called, here are the errors I am getting: [Caller Side 1](https://cdn.discordapp.com/attachments/747930605765001286/790604117222883358/unknown.png) | [Person being called side](https://cdn.discordapp.com/attachments/747930605765001286/790604186546602004/unknown.png) | [Caller Side 2](https://cdn.discordapp.com/attacments/747930605765001286/790604117222883358/unknown.png) | [Console Log](https://user-images.githubusercontent.com/69090660/102795755-40ac3c80-437b-11eb-815a-afedc05fe953.png)

Info:

ESX Version: 1.1
Artifacts: Latest
VOIP: Mumble (yes, it is set in the config)
Notes: Twitter works, texting works, and everything else works, there are no duplications in the database, and the only bug is that people are not receiving calls.

I saw that you had closed a previous issue about this ( #82 ), however I still cannot seem to find a fix for this, please respond when available, thank youuuuu :]

**Comment by RealGroddy** [comment]
Im having the same issue.

**Comment by joshua66553** [comment]
Init i am having the same error as well.

**Comment by RockySouthpaw** [comment]
Did all of you guys download from the release tab? This issue is something I personally tested with @itschip in my server on 1.1 and it worked fine for me. No issues. Even tested it with and a without a phone. There shouldn’t be anything even effecting this as the code for it wasn’t changed in a way that would effect this as there is still an if not for when the config item is is disabled.

 https://github.com/Re-Ignited-Development/Re-Ignited-Phone/commit/bf9d9ef5be85f053be3073d5d80366f6cf722509#diff-86a58c5db2e0171f3dffd2fa45577f029936d7f51ceb3f0ec81d3a36706d7bf6

You’re welcome to try and look at this commit where the item check is and see if it fixes anything but as I stated, I can’t personally reproduce this issue. I can try again later today for extra validation but the code looks fine.

**Comment by Itz-Hyperz** [comment]
[image](https://user-images.githubusercontent.com/69090660/102796800-cbda0200-437c-11eb-943f-d9abe101f036.png)
It is set to false, still have the same issue :[

**Comment by Itz-Hyperz** [comment]
Is it possible to simply just remove this line of code here: 
![image](https://user-images.githubusercontent.com/69090660/102797064-24a99a80-437d-11eb-970f-f09d42dcf94a.png)

**Comment by Itz-Hyperz** [comment]
Is it possible to simply just remove this line of code here: ![image](https://user-images.githubusercontent.com/69090660/102797234-68040900-437d-11eb-9abe-d9dcba32e89f.png)

**Comment by RockySouthpaw** [comment]
Lines 486-494 are the only portion related to triggering phone calls and the client event is the same as it always was.

**Comment by RockySouthpaw** [comment]
Im gonna make a new release in a few minutes so can try it

**Comment by Itz-Hyperz** [comment]
Okay, I appreciate it! Hopefully the new release will be able to fix this problem :]

**Comment by RockySouthpaw** [comment]
can all of you download it from https://github.com/Re-Ignited-Development/Re-Ignited-Phone/releases/tag/V1.5 and try again?

**Comment by Bandit-code** [comment]
I will try it!

**Comment by RockySouthpaw** [comment]
If it doesn't work take this:

```
            if srcTo ~= nill then
                AppelsEnCours[indexCall].receiver_src = srcTo
                TriggerEvent('gcPhone:addCall', AppelsEnCours[indexCall])
                TriggerClientEvent('gcPhone:waitingCall', sourcePlayer, AppelsEnCours[indexCall], true)
                local xPlayer = ESX.GetPlayerFromId(srcTo)
                local hasPhone  = xPlayer.getInventoryItem('phone').count
                print(hasPhone)
                if hasPhone >= 1 and Config.ItemRequired then
                    TriggerClientEvent('gcPhone:waitingCall', srcTo, AppelsEnCours[indexCall], false)
                elseif hasPhone == 0 then
                    print("no phone")
                elseif not Config.ItemRequired then
                    TriggerClientEvent('gcPhone:waitingCall', srcTo, AppelsEnCours[indexCall], false)
                end
            else
                TriggerEvent('gcPhone:addCall', AppelsEnCours[indexCall])
                TriggerClientEvent('gcPhone:waitingCall', sourcePlayer, AppelsEnCours[indexCall], true)
            end
        end)
  ```
 and replace it with this:
 
 ```
             if srcTo ~= nill then
                AppelsEnCours[indexCall].receiver_src = srcTo
                TriggerEvent('gcPhone:addCall', AppelsEnCours[indexCall])
                TriggerClientEvent('gcPhone:waitingCall', sourcePlayer, AppelsEnCours[indexCall], true)
                TriggerClientEvent('gcPhone:waitingCall', srcTo, AppelsEnCours[indexCall], false)
            else
                TriggerEvent('gcPhone:addCall', AppelsEnCours[indexCall])
                TriggerClientEvent('gcPhone:waitingCall', sourcePlayer, AppelsEnCours[indexCall], true)
            end
        end)
        ````
        
        This will revert the commit that does the item check, but i dont see a reason why it works for me and not you guys.

**Comment by Bandit-code** [comment]
What Version of ESX you on?

**Comment by RockySouthpaw** [comment]
i'm on 1.1

**Comment by RockySouthpaw** [comment]
Are people getting calls on the latest release? Before we delve in your mumble issue

**Comment by Itz-Hyperz** [comment]
nope, I am gonna exchange that code you sent previously now

**Comment by Itz-Hyperz** [comment]
yes!!!!!! Okay, we got calls working, and we can hear each other on the phone, however we cannot hear each other in normal game chat, you willing to help with that?

**Comment by RockySouthpaw** [comment]
Update me

**Comment by Itz-Hyperz** [comment]
Also, twitter isnt sending tweets :[

**Comment by Itz-Hyperz** [comment]
![image](https://user-images.githubusercontent.com/69090660/102802798-33944b00-4385-11eb-9097-62d563c8cded.png)

**Comment by RockySouthpaw** [comment]
You have to run the twitter SQL. Open a seperate issue for twitter.

No i can not provide support for getting your voip working.

As for the calling issue, did you ever try it with phone as an item == true?

**Comment by Itz-Hyperz** [comment]
Okay, thank you for your support, I will open an issue for twitter :]

Also yes, when it was true it did the same thing and had 0 effect on the issue.
