### ISSUE TITLE
Regarding Stock in the phone

### ISSUE THREAD

**Issue by joeng2645** [Re-Ignited-Development/Re-Ignited-Phone#88]
the stock app is not functioning no error message in f8 console or live console...
any tutorial on adding other apps to the phone like es_stockmarket etc
i would like to add apps into it

**Comment by RockySouthpaw** [comment]
What is not functioning about it?

**Comment by joeng2645** [comment]
i already insert all sql availble to my database i didnt see anything regarding to the stock
everything working good tip top shape... just the stock i open the app i try to buy i cant
i press enter to it but nothing happens

**Comment by joeng2645** [comment]
![20201222001348_1](https://user-images.githubusercontent.com/67365019/102797413-9ff56580-43ea-11eb-967b-9763e77f920c.jpg)
![20201222001352_1](https://user-images.githubusercontent.com/67365019/102797426-a1bf2900-43ea-11eb-89d4-135b98de09fd.jpg)

**Comment by joeng2645** [comment]
here are some screenshot i take

**Comment by RockySouthpaw** [comment]
200% sure that app is literally useless and doesn’t do shit lol idk why it even exist

**Comment by joeng2645** [comment]
omg
how do i add other stock market app to the phone

**Comment by joeng2645** [comment]
and i read the script there is a Config.AutoFindFixePhones but i cant find it in the config file

**Comment by joeng2645** [comment]
and i want to move the tweet nofitcation where can i move it i dont want it to be top right

**Comment by joeng2645** [comment]
> 200% sure that app is literally useless and doesn’t do shit lol idk why it even exist

please help me with 2 more question or problem thanks waiting forward for ur reply

**Comment by RockySouthpaw** [comment]
Open seperate issues. Do not use one issue for separate issues. The stock market isn’t going to be fixed so this is closed
