### ISSUE TITLE
Tweets wont send on Twitter app ESX 1.1

### ISSUE THREAD

**Issue by Itz-Hyperz** [Re-Ignited-Development/Re-Ignited-Phone#89]
So, I can create an account on the Twitter app, and when I go to send a tweet, it says it is sent, clears the input and all, but never adds that tweet to the database, I have ran the SQL file as shown here: 
![image](https://user-images.githubusercontent.com/69090660/102803313-10b66680-4386-11eb-837a-4aa7d9d62d96.png)

And now here is the error I get when I send a tweet in game: [Image 2](https://user-images.githubusercontent.com/69090660/102802798-33944b00-4385-11eb-9097-62d563c8cded.png)

**Comment by RockySouthpaw** [comment]
Truncate the column and re run the SQL

**Comment by Itz-Hyperz** [comment]
ngl, how would I go about "Truncating" it?

**Comment by RockySouthpaw** [comment]
I guess truncate might be the wrong word. Just remove the Twitter portion from your database and do a fresh install of it.

**Comment by Itz-Hyperz** [comment]
Okay, I dropped each twitter table, and re ran the SQL file for it, I'll update you after I test it.

**Comment by Itz-Hyperz** [comment]
Still not workng :[

**Comment by Itz-Hyperz** [comment]
Okay, I found a fix for this issue, at least a temporary one that hasn't affected anything else.

I simply just removed this line of code from the sending event:
`local srcIdentifier = ESX.GetPlayerFromId (_source).identifier`

So far everything still works just fine, and twitter is now fixed.
