### ISSUE TITLE
regarding the fix phones

### ISSUE THREAD

**Issue by joeng2645** [Re-Ignited-Development/Re-Ignited-Phone#92]
i found a config.autofindfixphone in the script server if i not mistaken and i notice that the config.lua didnt included it...so i added the config line to the config.lua and it works but i cant get to use the fix phone.. with or without adding line to config.lua the fix phone couldnt work at all... prompt the press e help message but when i press nothing happen as well as if the fixphone is ringing i try to press e to answer nothing happen too
![20201222200437_1](https://user-images.githubusercontent.com/67365019/102887184-6cb9e180-4491-11eb-8534-e871c2df5b88.jpg)

**Comment by BTNGaming** [comment]
Reboot your server when you add/edit it, just restarting the phone won't fix it.
