### ISSUE TITLE
Dont get a phone number at all

### ISSUE THREAD

**Issue by Goontje** [Re-Ignited-Development/Re-Ignited-Phone#93]
Hi there, i was looking for a GCPHONE plugin for ESX 1.1 then i found this one.
Finaly got it working (UI showing up) but i dont get a phone number, and due to that i cannot send messages or call the police for example.

I've followed every step in the manual, downloaded the files from the resource and replaced the server 1.1 file.

i also tried deleting the char, but that doenst work either.

Does anyone can help me to fix ?
Thank you very much.

**Comment by RockySouthpaw** [comment]
Did you download it from the release tab
