### ISSUE TITLE
the other party dont received any phone call

### ISSUE THREAD

**Issue by joeng2645** [Re-Ignited-Development/Re-Ignited-Phone#95]
![20201223005543_1](https://user-images.githubusercontent.com/67365019/102913355-9c7cdf80-44b9-11eb-8893-763462fc7a2b.jpg)
i call my fren to test the phone after i download the latest release but they dont received and ringtone

**Comment by RockySouthpaw** [comment]
You didn’t call them lol you need to include the dash so XXX-XXXX

**Comment by joeng2645** [comment]
![image](https://user-images.githubusercontent.com/67365019/102916515-a8b76b80-44be-11eb-968e-c64b287969c6.png)

**Comment by joeng2645** [comment]
> You didn’t call them lol you need to include the dash so XXX-XXXX

previously i enable this "useFormatNumberFrance"

**Comment by joeng2645** [comment]
the second photo i just upload i already disable "useFormatNumberFrance"

**Comment by joeng2645** [comment]
my fren didnt received any phone call

**Comment by joeng2645** [comment]
![image](https://user-images.githubusercontent.com/67365019/102916903-401cbe80-44bf-11eb-9214-2751f8c33603.png)
if my friend call my number my side phone ringing with ring tone working prefectly

**Comment by joeng2645** [comment]
update i call my friend the phone wont rang but if i end call my friend with appear my number with a miss call

**Comment by joeng2645** [comment]
it doesnt go with one sync right

**Comment by joeng2645** [comment]
The previous release before 21/12/2020 work just ok for phone calling not a problem at all i hope i can get some answer soon

**Comment by RockySouthpaw** [comment]
https://github.com/Re-Ignited-Development/Re-Ignited-Phone/issues/87#issuecomment-749064931

**Comment by RockySouthpaw** [comment]
I have no clue how this effect some people and not others but it has worked fine for me so

**Comment by joeng2645** [comment]
Is ok i found the problem the player must have the phone in inventory although we put the config item required as false

**Comment by joeng2645** [comment]
But for the fix line isnt working
