### ISSUE TITLE
Cannot use the inputs for contacts when Mouse Control is off. ESX 1.1

### ISSUE THREAD

**Issue by Itz-Hyperz** [Re-Ignited-Development/Re-Ignited-Phone#98]
When Mouse Control in the settings is off, so you use arrow keys, and you try to add a contact, you can't change anything in he inputs (Contact Name & Phone Number), you can only select the different buttons

**Comment by RockySouthpaw** [comment]
Can you post a video

**Comment by RockySouthpaw** [comment]
You have to press enter btw as a text box comes up
